spring:
  cloud:
    bus:
      enabled: true

security:
  oauth2:
    client:
      clientId: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
      clientSecret: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
    resource:
      token-info-uri: http://oauth-server/oauth/check_token
 
mail:
  registration-confirm:
    from: calendario.online.2020@gmail.com
    subject: Confirm Your Calendario Account
    templateName: registration-confirm
    url: http://172.16.8.177:4200/#/app/password/
  registration-success:
    from: calendario.online.2020@gmail.com
    subject: Calendario Account Active
    templateName: registration-success
url:
  oauth_server_save_password: http://oauth-server/savePassword
time:
  # 24h = 86400000 Milliseconds
  expiration-activeaccount: 86400000ms
  # 1h = 3600000 Milliseconds
  expiration-resetpassword: 3600000ms
      
message:
  registration-success: Please click on the link, that has been sent to your email account to verify your email and continue the registration process.
  registration-failed: Registration failed.
  registration-confirm-success: Your profile has been activated successfully. Password also changed.
  registration-confirm-failed: Unable to active account.
  email-exist: Email already exist.
  valid-token: Token is valid.
  invalid-token: Invalid token.
  invalid-access-token: Invalid access token.
  access-denied: User is not authorized to access the requested resource.
      