spring:
  cloud:
    gcp:
      project-id: '{cipher}AQCKpdalajLohLNmw5BZS5g2HKGc3MnPP0FwE7wiegATuLFLM8bDIGUrIfPXvbCAKNeOkRd+jqThHAtc4+ILSa0LZeUkHppXSdbqZN9ufyNUg5iQFbfuGEpdJxYjA5JVzQmwE8HtY+AHfk3evzWg8T7OqhqzaYE/z/4Uz412Srgd1QltSsAKl+n9KZ8mOq/WvowT1oIHXdGlxHUK17IrhrWsmny64HhLx7OCbjzH7eVTQjV+J2kY+98JvMb6x2tB+urPqZYdECZh/Zr9SpjFcQZCCVt+kz97/rBLekMlENeYeHaDou5uQ9gim2G/K9D/ueocM91j7L3+o5NxrSQ61t1mjxnuOebYLiszxzLuHuzzzM2iVF67OaKtU3W+2XuRaGtxmQq4bn2ieRXW6QTvwA7P'
    bus:
      enabled: true
  mail:
    username: calendario.online.2020@gmail.com
    password: "{cipher}AQCbB4RRXqZ3j2oH6vkSXfVE0x9T8lm616VGOkhLkGhpj7PSLAN3SZxiYOxeJber7eyg5BPWcfsuaXf+O9N/uCktkvoR4w8fP8zoXqOqXI6ASbZqK1fxgZD2r8TTiP0/vuZw/nv1AkJJWk4yuj18kmaMuUct3KcMOqD9EB/9a0zA6Z9lAsrG7FjMjKSQzm1+ukxPuzYPAy5orazpvwc9yWtNfHN0iBfpDXeWfYTh/sQgTqyGkQYR98IVOoOLQPRjaAeXstvCA4lqsUHl/EwlROc66LjGlGVyB0xg7q6hyQnc2632NgfNpqGPP6DyFxdEcAHG9DHH3dYaDO2GfEApt6L8FnrXXTPaei7XJAzJoMGtYXkzQBeaFOK5r1tMp7718Ao="
    host: smtp.gmail.com
    port: 587
    logging: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

management:
  endpoints:
    web:
      exposure:
        include: "*"
                