spring:
  cloud:
    gcp:
      project-id: '{cipher}AQCKpdalajLohLNmw5BZS5g2HKGc3MnPP0FwE7wiegATuLFLM8bDIGUrIfPXvbCAKNeOkRd+jqThHAtc4+ILSa0LZeUkHppXSdbqZN9ufyNUg5iQFbfuGEpdJxYjA5JVzQmwE8HtY+AHfk3evzWg8T7OqhqzaYE/z/4Uz412Srgd1QltSsAKl+n9KZ8mOq/WvowT1oIHXdGlxHUK17IrhrWsmny64HhLx7OCbjzH7eVTQjV+J2kY+98JvMb6x2tB+urPqZYdECZh/Zr9SpjFcQZCCVt+kz97/rBLekMlENeYeHaDou5uQ9gim2G/K9D/ueocM91j7L3+o5NxrSQ61t1mjxnuOebYLiszxzLuHuzzzM2iVF67OaKtU3W+2XuRaGtxmQq4bn2ieRXW6QTvwA7P'

management:
  endpoints:
    web:
      exposure:
        include: "*"
