spring:
  cloud:
    gcp:
      project-id: calendario-273709
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: calendario_vhost
    username: calendario
    password: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
  zipkin:
    base-url: 'http://zipkin'
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

# zuul:
#   sensitiveHeaders: Cookie,Set-Cookie
#   prefix: "/api"
#   ignoredServices: '*'
#   routes:
#     oauth-server:
#       path: /1.0/oauth-server/**
#       url: http://oauth-server/
#       strip-prefix: true
#     user-service:
#       path: /1.0/user-service/**
#       url: http://user-service/
#       strip-prefix: true

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    config-server:
      path: /config-server/**
      url: http://config-server/
    zipkin:
      path: /zipkin/**
      serviceId: zipkin
    rabbitmq:
      path: /rabbitmq/**
      serviceId: rabbitmq

ribbon: 
  eureka: 
    enabled: false

rabbitmq:
  ribbon:
    server: http://rabbitmq

zipkin:
  ribbon:
    server: http://zipkin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  